[workspace]

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "relayer-rest",
    "telemetry",
    "proto",
]

exclude = [
    "ci/no-std-check",
    "proto-compiler"
]

# [patch.crates-io]
# tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
[patch."https://github.com/paritytech/substrate"]
frame-support = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-system = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-session = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-client-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-keystore = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-network = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-network-gossip = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-application-crypto = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-arithmetic = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-blockchain = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-consensus = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-io = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-keystore = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-staking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-std = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-trie = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-prometheus-endpoint = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-benchmarking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-benchmarking-cli = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-assets = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-balances = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-staking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-im-online = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-transaction-payment-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-basic-authorship = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-chain-spec = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-cli = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-babe-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-epochs = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-slots = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-uncles = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-finality-grandpa-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-sync-state-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-authorship = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-timestamp = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-mmr-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-state-machine = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-babe = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-executor = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-finality-grandpa = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-rpc-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-service = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-telemetry = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-transaction-pool = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-block-builder = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-consensus-babe = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-finality-grandpa = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-inherents = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-frame-rpc-system = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-election-provider-support = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-executive = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-system-benchmarking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-system-rpc-runtime-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-authorship = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-babe = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-grandpa = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-mmr = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-randomness-collective-flip = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-staking-reward-curve = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-sudo = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-timestamp = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-transaction-payment = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-offchain = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-session = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-transaction-pool = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-version = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-wasm-builder = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-build-script-utils = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }

[patch.crates-io]
frame-support = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-system = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-session = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-client-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-keystore = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-network = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-network-gossip = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-application-crypto = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-arithmetic = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-blockchain = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-consensus = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-io = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-keystore = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-staking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-std = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-trie = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-prometheus-endpoint = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-benchmarking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-benchmarking-cli = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-assets = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-balances = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-staking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-im-online = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-transaction-payment-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-basic-authorship = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-chain-spec = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-cli = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-babe-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-epochs = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-slots = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-uncles = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-finality-grandpa-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-sync-state-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-authorship = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-timestamp = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-mmr-rpc = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-state-machine = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-consensus-babe = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-executor = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-finality-grandpa = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-rpc-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-service = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-telemetry = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sc-transaction-pool = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-block-builder = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-consensus-babe = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-finality-grandpa = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-inherents = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-frame-rpc-system = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-election-provider-support = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-executive = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-system-benchmarking = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
frame-system-rpc-runtime-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-authorship = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-babe = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-grandpa = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-mmr = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-randomness-collective-flip = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-staking-reward-curve = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-sudo = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-timestamp = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-transaction-payment = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-offchain = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-session = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-transaction-pool = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
sp-version = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-wasm-builder = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }
substrate-build-script-utils = { git = "https://github.com/octopus-network/substrate", branch = "polkadot-v0.9.12" }


## for tendermint
#tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
#tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
# ics23                   = { git = "https://github.com/informalsystems/ics23.git", branch = "master" }
# safe-regex          = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
# safe-regex-macro    = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
# safe-regex-compiler = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
# safe-quote          = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
# safe-proc-macro2    = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
# tonic = { package = "informalsystems-tonic", git = "https://github.com/informalsystems/tonic.git", branch = "thane/informal-0.5.2" }

tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
ics23                   = { git = "https://github.com/informalsystems/ics23.git", rev = "4461b673" }
safe-regex          = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-regex-macro    = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-regex-compiler = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-quote          = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-proc-macro2    = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
tonic = { package = "informalsystems-tonic", git = "https://github.com/informalsystems/tonic.git", rev = "99edfe23" }

[patch."https://github.com/octopus-network/ibc-rs"]
ibc = { path = "./modules" }
ibc-proto = { path = "./proto" }

